spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ITS
    username: postgres
    password:
    driver-class-name: org.postgresql.Driver
  devtools:
    restart:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

# Optional: server port
server:
  port: 8080

# Logging (optional)
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
